=== danielmartinan/linguaxes_marcas_2025-26/docs/_examenes/examen_T2/solucion/ejer2/formula1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:simpleType name="rolType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="titular"/>
      <xs:enumeration value="reserva"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="motorType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ferrari"/>
      <xs:enumeration value="Mercedes"/>
      <xs:enumeration value="Honda"/>
      <xs:enumeration value="Ford"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tipoCircuitoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="urbano"/>
      <xs:enumeration value="permanente"/>
      <xs:enumeration value="semiurbano"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dorsalType">
    <xs:restriction base="xs:positiveInteger">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="99"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="presupuestoType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="longitudKmType">
    <xs:restriction base="xs:decimal">
      <xs:minExclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="personaType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="nacionalidad" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="pilotoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="dorsal" type="dorsalType"/>
      <xs:element name="nacionalidad" type="xs:string"/>
      <xs:element name="rol" type="rolType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="circuitoType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="pais" type="xs:string"/>
      <xs:element name="longitudKm" type="longitudKmType"/>
      <xs:element name="tipo" type="tipoCircuitoType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="escuderiaType">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="paisBase" type="xs:string"/>
      <xs:element name="jefeEquipo" type="personaType"/>
      <xs:element name="pilotos">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="piloto" type="pilotoType" minOccurs="2" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="motor" type="motorType"/>
      <xs:element name="presupuesto" type="presupuestoType"/>
      <xs:element name="circuitosHabituales" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="circuitoHabitual" type="circuitoType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="codigo" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="temporadaF1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="escuderia" type="escuderiaType" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element name="circuito" type="circuitoType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="codigoEscuderiaUnico">
      <xs:selector xpath="escuderia"/>
      <xs:field xpath="@codigo"/>
    </xs:unique>

    <xs:unique name="dorsalPilotoUnico">
      <xs:selector xpath="escuderia/pilotos/piloto"/>
      <xs:field xpath="dorsal"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== danielmartinan/linguaxes_marcas_2025-26/docs/_examenes/examen_T2/recursos_examen_T2/ejer2/formula1.xml
<?xml version="1.0" encoding="UTF-8"?>
<temporadaF1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="formula1.xsd">
  <escuderia codigo="MER">
    <nombre>Mercedes-AMG Petronas</nombre>
    <paisBase>Alemania</paisBase>
    <jefeEquipo>
      <nombre>Toto Wolff</nombre>
      <nacionalidad>Austriaco</nacionalidad>
    </jefeEquipo>
    <pilotos>
      <pilotoTitular>
        <nombre>Kimi Antonelli</nombre>
        <dorsal>12</dorsal>
        <nacionalidad>Italiano</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
      <pilotoTitular>
        <nombre>George Russell</nombre>
        <dorsal>63</dorsal>
        <nacionalidad>Británico</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
    </pilotos>
    <motor>Mercedes</motor>
    <presupuesto>450.5</presupuesto>
    <circuitosHabituales>
      <circuitoHabitual>
        <nombre>Silverstone</nombre>
        <pais>Reino Unido</pais>
        <longitudKm>5.891</longitudKm>
        <tipo>permanente</tipo>
      </circuitoHabitual>
    </circuitosHabituales>
  </escuderia>

  <escuderia codigo="FER">
    <nombre>Scuderia Ferrari</nombre>
    <paisBase>Italia</paisBase>
    <jefeEquipo>
      <nombre>Frederic Vasseur</nombre>
      <nacionalidad>Francés</nacionalidad>
    </jefeEquipo>
    <pilotos>
      <pilotoTitular>
        <nombre>Charles Leclerc</nombre>
        <dorsal>16</dorsal>
        <nacionalidad>Monegasco</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
      <pilotoTitular>
        <nombre>Lewis Hamilton</nombre>
        <dorsal>44</dorsal>
        <nacionalidad>Británico</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
    </pilotos>
    <motor>Ferrari</motor>
    <presupuesto>400.0</presupuesto>
    <circuitosHabituales>
      <circuitoHabitual>
        <nombre>Monza</nombre>
        <pais>Italia</pais>
        <longitudKm>5.793</longitudKm>
        <tipo>permanente</tipo>
      </circuitoHabitual>
    </circuitosHabituales>
  </escuderia>

  <escuderia codigo="MCL">
    <nombre>McLaren Formula 1 Team</nombre>
    <paisBase>Reino Unido</paisBase>
    <jefeEquipo>
      <nombre>Andrea Stella</nombre>
      <nacionalidad>Italiano</nacionalidad>
    </jefeEquipo>
    <pilotos>
      <pilotoTitular>
        <nombre>Lando Norris</nombre>
        <dorsal>4</dorsal>
        <nacionalidad>Británico</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
      <pilotoTitular>
        <nombre>Oscar Piastri</nombre>
        <dorsal>81</dorsal>
        <nacionalidad>Australiano</nacionalidad>
        <rol>titular</rol>
      </pilotoTitular>
      <pilotoReserva>
        <nombre>Leonardo Fornaroli</nombre>
        <dorsal>20</dorsal>
        <nacionalidad>Italiano</nacionalidad>
        <rol>reserva</rol>
      </pilotoReserva>
      <pilotoReserva>
        <nombre>Patricio 'Pato' O'Ward</nombre>
        <dorsal>5</dorsal>
        <nacionalidad>Mexicano</nacionalidad>
        <rol>reserva</rol>
      </pilotoReserva>
    </pilotos>
    <motor>Mercedes</motor>
    <presupuesto>420.0</presupuesto>
    <circuitosHabituales>
      <circuitoHabitual>
        <nombre>Suzuka</nombre>
        <pais>Japón</pais>
        <longitudKm>5.807</longitudKm>
        <tipo>permanente</tipo>
      </circuitoHabitual>
    </circuitosHabituales>
  </escuderia>

  <circuito>
    <nombre>Bahrain International Circuit</nombre>
    <pais>Baréin</pais>
    <longitudKm>5.412</longitudKm>
    <tipo>permanente</tipo>
  </circuito>
  <circuito>
    <nombre>Circuit de Monaco</nombre>
    <pais>Mónaco</pais>
    <longitudKm>3.337</longitudKm>
    <tipo>urbano</tipo>
  </circuito>
  <circuito>
    <nombre>Yas Marina Circuit</nombre>
    <pais>Emiratos Árabes Unidos</pais>
    <longitudKm>5.281</longitudKm>
    <tipo>semiurbano</tipo>
  </circuito>
</temporadaF1>
